config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'store/index'

  # get 'article/index'
  #
  # get 'book/index'

  resources :products  #对应products——controller
  resources :book
  resources :article #对应article——controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to=>'book#index'
  # 以下是定义根网址的，as部分是告诉rails创建store_path的变量
  root :to=>'store#index',:as=>'store'
end

app/models/book.rb
class Book < ApplicationRecord

end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
    @books=Book.all
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @book = Book.where("id = #{params[:id]}").first
    # @book = Book.where("id =  ? ", params[:id]).first
    # @book = Book.find params[:id]
  end

  def new
  end

  def create
    Book.create :name => params[:name], :title=>params[:title], :author=>params[:author]
    redirect_to book_index_path
  end

  def edit
    # 以下三种写法都可以。 一般用find
    # @book = Book.where("id = #{params[:id]}").first
    # @book = Book.where("id =  ? ", params[:id]).first
    @book = Book.find params[:id]
  end

  def update
    book=Book.find(params[:id])
    book.title=params[:title]
    book.name=params[:name]
    book.author=params[:author]
    book.save
    redirect_to book_index_path
  end

def destroy
  @book = Book.where("id=#{params[:id]}").first
  @book.delete
  redirect_to root_path
end

end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/edit.html.erb
<form action='/book/<%=@book.id %>' method='POST'>
<input type='hidden' name='_method' value='put' />
title:<input type='text' name='title' value=<%= @book.title  %>/>
  </br>
  name:<input type='text' name='name' value=<%= @book.name  %>/>
  </br>
  author:<input type='text' name='author' value=<%= @book.author %> />
  </br>
  <input type='submit' value='确定'/>
</form>

app/views/book/index.html.erb
<h1>Book#index</h1>
<%= link_to 'new', new_book_path%>
<%  @books.each do |e|  %>
    <p>
         <%= e.inspect %>
         <%= link_to '编辑', edit_book_path( :id => e.id )%>
         <%= link_to '详情', book_path( :id => e.id )%>
         <%= link_to 'Delete', "/book/#{e.id}",data:{:confirm => '确定删除?'},:method=>'delete'%>
    </p>
<%  end  %>

app/views/book/new.html.erb
<form action='/book' method='POST'>
title:<input type='text' name='title' value="1111" />
  </br>
  name:<input type='text' name='name' value="1111" />
  </br>
  author:<input type='text' name='author'  value="1111" />
  </br>
  <input type='submit' value='确定'/>
</form>

app/views/book/show.html.erb
<h3>详情页</h3>
<%= @book.title %>
<br>
<%= @book.name %>
<br>
<%= @book.author %>
<br>
<%= link_to 'Back', root_path( :id => @book.id )%>