config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'store/index'

  # get 'article/index'
  #
  # get 'book/index'

  resources :products  #对应products——controller
  resources :book
  resources :article #对应article——controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to=>'book#index'
  # 以下是定义根网址的，as部分是告诉rails创建store_path的变量
  root :to=>'store#index',:as=>'store'
end

app/models/cart.rb
class Cart < ApplicationRecord
  # 一个购物车有多个在线商品，购物车删除之后，对应的加到购物车中的在线商品也要清空，也就是
  # 清空line_item中与之关联的数据
  has_many :line_item,:dependent => :destroy
  def add_product(product_id)
    current_item=line_item.find_by_product_id(product_id);
    if current_item
      current_item.quantity +=1;
    else
      current_item=line_item.build(:product_id=>product_id);
    end
    return current_item;
  end

  def total_price
    line_item.to_a.sum{|item| item.total_price}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    @cart=current_cart
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error '无效的购物车请求 #{:param[:id]}'
      redirect_to store_url, :notice=>'无效的购物车'
    else
      respond_to do |formart|
        formart.html
        formart.xml {render :xml=>@cart}
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: '购物车成功创建.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: '购物车更新成功.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart=current_cart
    @cart.destroy
    session[:cart_id]=nil
    respond_to do |format|
      format.html { redirect_to carts_url, notice: '购物车删除成功.' }
      format.xml {head :ok}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_cart
    #   begin
    #     @cart = Cart.find(params[:id])
    #   rescue ActiveRecord::RecordNotFound
    #     logger.error "无效的购物车请求 #{:param[:id]}"
    #     redirect_to store_url, :notice=>'无效的购物车'
    #   else
    #     respond_to do |formart|
    #       formart.html
    #       formart.xml {render :xml=>@cart}
    #     end
    #   end
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<p id="notice"><%= notice %></p>
<h2>购物车详情</h2>
<div id="store" class="cart_title">
  <table>
    <tr>
      <th>产品</th>
      <th>数量</th>
      <th>单价</th>
      <th>总价</th>
    </tr>
    <%= render(@cart.line_item) %>
    <tr class="total_line">
      <td colspan="3"></td>
      <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>
  </table>
</div>


<%= link_to '编辑', edit_cart_path(@cart) %> |
<%= link_to '返回', carts_path %>
<%= button_to '清空购物车',@cart,:method=>:delete,:confirm=>'确认删除？' %>

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>编辑购物车</h1>

<%= render 'form', cart: @cart %>

<%= link_to '查看', @cart %> |
<%= link_to '返回', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>购物车</h1>

<table>
  <thead>
    <tr>
      <th>购物车ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.id %></td>
        <td><%= link_to '查看', cart %></td>
        <td><%= link_to '编辑', edit_cart_path(cart) %></td>
        <td><%= link_to '删除', cart, method: :delete, data: { confirm: '确定删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建购物车', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to '返回', carts_path %>

app/views/carts/show.html.erb
<%= render(@cart) %>