config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'store/index'

  # get 'article/index'
  #
  # get 'book/index'

  resources :products  #对应products——controller
  resources :book
  resources :article #对应article——controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to=>'book#index'
  # 以下是定义根网址的，as部分是告诉rails创建store_path的变量
  root :to=>'store#index',:as=>'store'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  # 一个商品对应关系是依赖于product和cart的
  belongs_to :product
  belongs_to :cart
  def total_price
    quantity*product.price
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
    @cart=current_cart
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @cart=current_cart
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
    @cart=current_cart
  end

  # GET /line_items/1/edit
  def edit
    @cart=current_cart
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart=current_cart
    begin
      # store添加到购物车
      @product=Product.find(params[:product_id]);
    rescue ActiveRecord::RecordNotFound
      #购物车列表中添加时由于传递的param是line_item,所以用下面的方式获取
      begin
        @product=Product.find(line_item_params[:product_id]);
      rescue ActiveRecord::RecordNotFound
        logger.error '无效的购物车商品请求 #{line_item_params[:product_id]}'
        redirect_to line_items_path, :notice=>'没有对应的商品'
      end
    else
      # @line_item=@cart.line_item.build(:product=>product)
      @line_item=@cart.add_product(@product.id);
      respond_to do |format|
        if @line_item.save
          format.html{redirect_to(store_path,:notice => 'Line Item 创建成功')}
          format.xml{render :xml=>@line_item,:status => :created,:location => @line_item}
        else
          format.html{render :action => 'new'}
          format.xml{render :xml=>@line_item.errors,:status => :unprocessable_entity}
        end
      end
    end

  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: '购物车明细更新成功.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    # LineItem.find(params[:id]).destroy;
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: '购物车明细删除成功.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(line_item) do |f| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :cart_id %>
    <%= f.number_field :cart_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td><%= line_item.product.title %></td>
  <td><%= line_item.quantity %></td>
  <td class="item_price"><%= number_to_currency(line_item.product.price) %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to '查看', @line_item %> |
<%= link_to '返回', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>购物明细列表</h1>

<table>
  <thead>
    <tr>
      <th>产品ID</th>
      <th>购物车ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to '查看', line_item %></td>
        <td><%= link_to '编辑', edit_line_item_path(line_item) %></td>
        <td><%= link_to '删除', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建购物明细', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to '返回', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>商品:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>购物车:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to '编辑', edit_line_item_path(@line_item) %> |
<%= link_to '返回', line_items_path %>